### ISSUE TITLE
endpoint URL needs to be updated

### ISSUE THREAD

**Issue by bseeger** [RubenVerborgh/Refine-NER-Extension#13]
The URI for the spotlight service has changed.  I think this code: 

https://github.com/RubenVerborgh/Refine-NER-Extension/blob/master/src/org/freeyourmetadata/ner/services/DBpediaSpotlight.java#L20

Needs to be updated to point to: 
http://demo.dbpedia-spotlight.org/

Or, better yet, make the URI configurable in the extension.

**Comment by RubenVerborgh** [comment]
Thanks, released as v1.4.1.
