### ISSUE TITLE
API retired

### ISSUE THREAD

**Issue by Phu2** [RubenVerborgh/Refine-NER-Extension#14]
- Alchemy API retired, see https://www.ibm.com/blogs/bluemix/2017/03/bye-bye-alchemyapi/ therefore https://www.alchemyapi.com/api/register.html  no longer works
- WikiMeta is gone, 404 for http://www.wikimeta.com/api.html
- Zemanta also vanished: http://developer.zemanta.com/member/register/

**Comment by RubenVerborgh** [comment]
Thanks for reporting. It is probably time to retire this extension then as well. I will archive this repository.
